### ISSUE TITLE
Release of pwsafe for Manjaro-Linux distribution

### ISSUE THREAD

**Issue by asob** [pwsafe/pwsafe#1073]
Hi, 

I've recently switched from Windows to Manjaro and would like to be able to continue using this awesome piece of software on Manjaro.

**Comment by ronys** [comment]
Hi,

I've recently created a package for Arch Linux. Let me know if you'd like to see if it works under Manjaro.

**Comment by embozepho** [comment]
Hello. I am also interested in Password Safe for Manjaro.
I'm working on moving away from Fedora, and have installed a Manjaro-Gnome, and a Manjaro-Cinnamon to see which one I might use. I will probably try some of the other Manjaro GUI's, and possibly some other Arch distros. Would be happy to try the Arch package on any of those I set up.

**Comment by EzraZerba** [comment]
Hi. I am trying to move from Windows 10 to Linux since Windows 11 doesn't support my hardware.
(And I've wanted to do it anyway.)

I've installed Arch Mangaro with KDE Plasma.
I was sad to find out that after getting it installed, that PasswordSafe, one of the first things that I want to install, isn't available on this distro.

Do you think this Arch version will come soon?
Do you think it will work on Mangaro with KDE Plasma?

**Comment by igor2x** [comment]
Currently there are only [official Linux native packages](https://github.com/pwsafe/pwsafe/releases?q=non-windows&expanded=true) for Debian, Fedora, Linux Mint and Ubuntu brought to from pwsafe.org project. There maybe some unofficial builds somewhere for other Linux distributions or versions provided by Linux distribution package maintainers.

---

But... you can install Passworrd Safe v1.18.2 as a flatpak, that is officially [supported on 36 Linux distributions.](https://flatpak.org/setup/) There are two steps required:
1. [Install flatpak support](https://www.flatpak.org/) on Manjaro.
2. [Install Password Safe flatpak.](https://flathub.org/apps/org.pwsafe.pwsafe)

Flatpak is specially useful for people that are jumping from one Linux distribution to another, because flatpak is exactly the same on all of Linux distribution flatpak is supported on.

Because Password Safe v1.18.2 is new to flatpak distribution (it is only two weeks old) there are some small issues on it (please read the following issues before reporting a new one) :
- Password Safe flatpak issues [reported on Flathub](https://github.com/flathub/org.pwsafe.pwsafe/issues)
- Password Safe flatpak issues [reported on Password Safe
](https://github.com/flathub/org.pwsafe.pwsafe/issues)

**Comment by ronys** [comment]
> Hi. I am trying to move from Windows 10 to Linux since Windows 11 doesn't support my hardware. (And I've wanted to do it anyway.)
> 
> I've installed Arch Mangaro with KDE Plasma. I was sad to find out that after getting it installed, that PasswordSafe, one of the first things that I want to install, isn't available on this distro.
> 
> Do you think this Arch version will come soon? Do you think it will work on Mangaro with KDE Plasma?

In addition to the flatpak that @igor2x mentioned, you should be able to use the PKGBUILD file in install/arch to build and install PasswordSafe on Manjaro.

Please reopen this ticket if you need more help.
