### ISSUE TITLE
Flatpak 1.18.2 cannot access files in my home directory

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1094]
I installed the new Flatpak version of PasswordSafe on Fedora 39 using the Gnome Software utility.  On first launch, it could not access my home directory where my existing DB was located.  I was able to create a new DB and, from the shell, I was able to copy the existing DB to the sandbox and open it.  (~/.var/app/org.pwsafe.pwsafe/config/pwsafe/).  After learning about flatseal from #1091 (thanks @igor2x), I was able to change the settings.  I could enable "All user files" or add ~/.pwsafe to the "Other files" list.  Either way gave me access to the file.  

I can see this being a stumbling block for users switching from the dedicated builds to flatpak.  Since it's reasonable to assume a user would have saved their DB somewhere under their own home directory, but maybe not in .pwsafe, I suggest enabling "All user files" access.

**Comment by igor2x** [comment]
Ordinary applications installed with deb/rpm packages have full control of your computer. Which is OK, if you really trust developer (why should you?) or you are capable and having time to inspect the source code. Allowing application to have full access to all of your computer resources was fine when there was no interconnection with the outside world and so application could never "call home". Now imagine you have some nasty application that collects all kind of your personal data and just sends them "home".

The idea of flatpak is to restrict some of the rights of application. Application is therefore sandboxed and it is strictly defined what computer resource can application access outside of its sandbox. This is pretty similar to mobile applications that have pretty restrictive access to the mobile phone. For example at Android phone you go to Settings | Apps | "application" |  Permissions and you can allow or restrict permissions. Similar logic is with flatpak applications where you can use application like Flatseal to grant permissions. This may be pretty new idea for a lot of people on personal computers and that is why it looks so strange. 

By the way @ronys is Password Safe developer, but I have packaged application as flatpak and together we were doing everything to be published on Flathub.org. When I have been in the process of creating a flatpak package I read tons of documentation and in documentation is strictly written to assign flatpak package as least of permissions as possible. Whole flatpak procedure is transparent and flatpak mergers personal inspect the build procedure and can easily stop you from publishing package to Flathub.org if there are too many permissions.

When I have been building flatpak I was thinking like this, default location of Password Safe application is  /home/"user"/.var/app/org.pwsafe.pwsafe/config/pwsafe which may be too complicated for users to remember of then find location of file when they try to for example backup it. That is why I have also assigned permission to the /home/"user"/Document directory and allowed user to save files to one of the sub-directory if he/she likes to have more human readable directory that the files are stored into.

In general it is pretty bad idea to allow flatpak application to access all of the files/directories on your computer. You are throwing away one of the greatest benefits of flatpak, to restrict application inside sandox.

@ronys, just in case if there is need to assign more rights to more directories there is the following documentation to [allow sandbox permissions](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html) and the changes are only required to be made on [pwsafe/flahab](https://github.com/flathub/org.pwsafe.pwsafe/blob/master/org.pwsafe.pwsafe.yml) file for each of directory for documentation a new line with `--filesystem` parameter.

@nobugshere, in my humble opinion it is also not the best idea to save files in $HOME/.pwsafe directory because a lot of other applications could access this folder and so they could "send home" your Password Safe database.

The safest location is to have Password Safe inside $HOME/.var/app/org.pwsafe.pwsafe/config/pwsafe that no other flatpaks can access. But if you prefer you can also safe it to the $HOME/Documents or one of sub-folders.

@ronys, I agree with you that for now we should not assign more permissions, what we could do is some explanation, maybe in Flathub default Password Safe web page. Like: _Application is restricted to access only $HOME/.var/app/org.pwsafe.pwsafe/config/pwsafe or $HOME/Documents. If you need some other directory to save your Password Safe database, then you can assign more right with Flatseal application._ What do you think about this idea, to add more info to flatpak description?
