### ISSUE TITLE
macOS: Master Password Entry dialog box resizes after it's displayed

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1302]
A quick look at version 1.19 on the Mac revealed a small regression. In 1.18.2, the "Master Password Entry" dialog appears with some empty space that is filled-in if a yubikey is inserted. In 1.19, the dialog initially appears with the extra space then, about a second later, the window shrinks. (I speculate the delay is related to the Yubikey timeout.) If a Yubikey is inserted, it re-expands and displays the button and text as normal. From a user perspective, the aesthetics of a dialog with some extra empty space is preferable to one that suddenly shrinks after it appears. More discussion is in #1299.

This problem does not happen on my Fedora VM. The window appears without the blank space, then expands when a key is inserted.

macOS M1Max Sonoma 14.5, Xcode 15.4, wx 3.2.4
Fedora 40 ARM64, Xfce/X11, gcc 14.1.1, wx 3.2.4, GTK 3.24.42

**Comment by igor2x** [comment]
I have downloaded the latest master from Github/Actions on Ubuntu 22.04 and I see this too
- Master Password Entry shrinks like 1 second after it appears
- the same with Manage | Change Master Password also dialog shrinks like 1 second after it apepars.

This is not only regression from v1.18.2, but also a regression from like one or two commits ago... It has to be very recent change and not specific to macOS, because I am on Ubuntu.

My system Ubuntu 22.04 with Help | About:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/417a1643-18f7-41e2-85bd-f42a04caa465)

**Comment by nobugshere** [comment]
Fixed by #1309
