### ISSUE TITLE
Looking for a  passwordsafe-ubuntu22-1.19-amd64.deb Build

### ISSUE THREAD

**Issue by user-629782** [pwsafe/pwsafe#1313]
Please provide an Ubuntu 22.04 Build for amd64 architecture.

Thank you

**Comment by igor2x** [comment]
Currently Password Safe v1.19 for Ubuntu 22.04 is not available from official download page. I don't know why, probably nobody requested it yet. I am sure @ronys will add the deb package when he will have some spare time.

---

But... you can download Password Safe v1.19 for Ubuntu 22.04 from Github/Actions. The requirement is you have to sign in to Github and then click on https://github.com/pwsafe/pwsafe/actions/runs/9428658052 unzip file and there is deb file inside.

**Just a caution!**
If you are using Ubuntu 22.04 with Wayland, check in terminal: `echo $XDG_SESSION_TYPE` if "wayland" is displayed, then I suggest to not install this Password Safe v1.19, because there is currently pretty [nasty bug](https://github.com/pwsafe/pwsafe/issues/1308) in it that on copying password Ubuntu session gets crashed and you need to relogin into Ubuntu again. [Pull request 1310](https://github.com/pwsafe/pwsafe/pull/1310) was prepared and is waiting be merged into master branch and then new minor Password Safe v1.19.x version is released. @ronys, the project leader is pretty busy and like I communicated with him over e-mail, he will not be available until next week.

**Comment by user-629782** [comment]
Thanks so much @igor2x for the information. Yes, I am running Wayland so I will wait until the commits settle, especially #1310.
Thanks for saving me some pain....

**Comment by igor2x** [comment]
@ronys, today Password Safe v1.19.1 was released for Linux. Can you please build Password Safe for Ubuntu 22.04.
Ubuntu releases every 6 mounts, but every 2 years it releases LTS version that is then supported for 10 years (or 12 years...). Ubuntu LTS releases:
- Ubuntu 20.04 LTS  (released: April 2020) --> Password Safe v1.19.1 exists
- Ubuntu 22.04 LTS (released: April 2022)  --> Password Safe v1.19.1 is **missing**
- Ubuntu 24.04 LTS (release: April 2024) --> Password Safe v1.19.1 exists

Currently latest LTS release is Ubuntu 24.04, but majority of people are on Ubuntu 22.04, because before first fix level is released (24.04.1) upgrades to never LTS versions are not offered to people.

**Comment by ronys** [comment]
Done:
https://github.com/pwsafe/pwsafe/releases/download/1.19.1/passwordsafe-ubuntu22-1.19.1-amd64.deb

**Comment by user-629782** [comment]
Thank you both @ronys for generating the release and @igor2x for keeping it relevant.
