### ISSUE TITLE
Can't start pwsafe: Assertion '__n < this->size()' failed

### ISSUE THREAD

**Issue by wohler** [pwsafe/pwsafe#1329]
I just installed pwsafe via flatpak and am not able to start the program. I get the following error:

    $ flatpak run org.pwsafe.pwsafe
    /usr/include/c++/13.2.0/bits/stl_vector.h:1125: std::vector<_Tp,_Alloc>::reference
    std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp =
    std::__cxx11::basic_string<wchar_t>; _Alloc =
    std::allocator<std::__cxx11::basic_string<wchar_t> >; reference =
    std::__cxx11::basic_string<wchar_t>&; size_type = long unsigned
    int]: Assertion '__n < this->size()' failed.

I was hopeful that the fix for issue #1327 would have taken care of it, but perhaps I have a slightly different issue. Here's my version. Note that the version in the metadata differs from the commit.

    $ flatpak info org.pwsafe.pwsafe

    Password Safe - Password management utility

	      ID: org.pwsafe.pwsafe
	     Ref: app/org.pwsafe.pwsafe/x86_64/stable
	    Arch: x86_64
	  Branch: stable
	 Version: v1.18.2
	 License: Artistic-2.0
	  Origin: flathub
      Collection: org.flathub.Stable
    Installation: user
       Installed: 45.3 MB
	 Runtime: org.freedesktop.Platform/x86_64/23.08
	     Sdk: org.freedesktop.Sdk/x86_64/23.08

	  Commit: 871486fabf4e6f7c8ae62b3625fe4bd3ccd9272a767599e731a1af0950d966c6
	  Parent: 17893d5acce968a86b739d30910f7f4f9099393c9ac109c2caaf9037569c0841
	 Subject: Update flatpak to 1.19.1 (9ebe6b5e)
	    Date: 2024-07-05 11:27:35 +0000

Interestingly, I *think* I am running 1.19 at work via flatpak successfully. It's a Red Hat 8 system. My home system (for this report) is Debian GNU/Linux 12 (bookworm).

**Comment by ronys** [comment]
This bug is triggered by an empty list of recently opened safes, which probably explains why you see it on your work environment but not at home.
In any case, flatpak was recently updated to 1.19.1, you might want to try that version.

**Comment by wohler** [comment]
Thanks Rony and Igor. I found a workaround. 

In my Red Hat environment at work, the error messages made it very clear that the flatpak version of pwsafe didn't have visibility to my ~/.pwsafe directory, so I had added a  `--filesystem=~/.pwsafe` option.

Tonight I added the `--filesystem` option and ran the following on my home system--et viola!--the login dialog appeared!

    flatpak run --filesystem=~/.pwsafe org.pwsafe.pwsafe

A couple of thoughts:

1. If this bug was fixed in 1.19.1, I should not have seen it since I am running 1.19.1 (it appears that the flatpak metadata is incorrect). The Password Safe login dialog clearly says V1.19.1.
2. There may be an issue with the Debian installation of flatpak versus the Red Hat installation that turns a usable error message such as "~/.pwsafe: permission denied" into an unusable message like "Assertion '__n < this->size()' failed."

**Comment by ronys** [comment]
Thanks for the update.
Re your second comment: I doubt it, since that error message is what's printed when the bug I mentioned was triggered.

**Comment by wohler** [comment]
I'm not sure I follow. I've been running pwsafe on my systems for years (for which I am very appreciative, by the way!) which means that my pwsafe environment (~/.pwsafe directory) on my systems is pretty much the same. I installed pwsafe via flatpak on my work system on 2024-06-11, which was before you fixed this bug, right? I never saw this assertion output at work. I think my error messages at the time were closer to "file not found." I specified the database on the command line in both cases.

**Comment by nobugshere** [comment]
I can reproduce this problem on Fedora, with the current flatpack release, if I do not already have a pwsafe.cfg file in ~/.var/app/org.pwsafe.pwsafe/config/pwsafe. (As would be the case on first run.) I can *not* reproduce it with my native build.

Fedora 40 ARM64 VMware, Xfce/X11, gcc 14.1.1, wx 3.2.4, GTK 3.24.42

**Comment by igor2x** [comment]
> There may be an issue with the Debian installation of flatpak versus the Red Hat installation

From the concept that flatpak should behave the same independent of host Linux distribution. Maybe you have different version of flatpak as infrastructure software. Can you please execute `flatpak --version` on Debian and Red Hat.

> which means that my pwsafe environment (~/.pwsafe directory) on my systems is pretty much the same

Native installations of Password Safe uses ~/.pwsafe directory for storing configuration files. But flatpak versions should use standard flatpak path ~/.var/app/FLATPAK_NAME like .var/app/org.pwsafe.pwsafe.

I assume latest Password Safe v1.19.1 flatpak version has some issue of creating new configuration files if configuration files are missing (like on the first install) or are intentionally deleted, like I did tests in [issue 1334](https://github.com/pwsafe/pwsafe/issues/1334#issuecomment-2218692594) I have reported (because this issue was closed).

Executing `--filesystem=~/.pwsafe` in your case I assume pointed Password Safe v1.19.1 flatpak to the remains of Password Safe installed as native package (.deb or .rpm) that where not cleansed after (I assume) you have removed removed native package.

**Comment by wohler** [comment]
Hey Igor,

Here's what I see for flatpak versions:

work: Flatpak 1.12.9
home: Flatpak 1.14.8

As a reminder, when I set up flatpak pwsafe at work, I never saw the assertion error, but I saw it at home. Since I set up pwsafe at work a month ago, I believe that was before 1.19 was out. Do you think the flatpak version may explain the difference?

Thanks for pointing out that the flatpak version of pwsafe is looking to ~/.var/app/org.pwsafe.pwsafe/config/pwsafe for the database. I'm not quite ready to switch to that directory for interoperability reasons. So yes, I'm retaining the native ~/.pwsafe location for the Password Safe database. For now.

And yes, I'll be deleting the native Debian package soon...done.

**Comment by igor2x** [comment]
> As a reminder, when I set up flatpak pwsafe at work, I never saw the assertion error, but I saw it at home. Since I set up pwsafe at work a month ago, I believe that was before 1.19 was out.

A month ago you have set up Password Safe v1.18.2 flatpak version (because there was no v1.19.x at the time) and this version works fine on clean install or on upgrade. Upgrading from already working Password Safe flatpak also works in v1.19.1.

The problem only appears if Password Safe v1.19.1 flatpak is installed as clean install (no previous Password Safe flatpak was installed). This is the issue/bug.

But I assume at home you did not have Password Safe v1.18.2 flatpak installed, but you have clean installed Password Safe v1.19.1 flatpak that is causing problem if config files are not already present in ~/.var/app/org.pwsafe.pwsafe/ It is just some bug in v1.19.1.

>Do you think the flatpak version may explain the difference?

You are referring to different crash error message when starting Password Safe. I don't know. I have never got different error message running on different Linux distributions. Probably I have used pretty much the same flatpak software. Like I see Red Hat 8 is not using the latest flatpak software (`flatpak --version`) and that is why it is possible that you have seen different crash error message on Red Hat vs. Debian.

I think that Linux distribution alone should not affect the flatpak's error message, but the error is from one of other layers. Layers:
- Linux distribution (Debian, Red Hat...).
- Flatpak software (`flatpak --version`) installed from [Linux distribution repository.](https://flatpak.org/setup/)
- Flatpak runtime (`flatpak list --runtime`) and see which one is using Password Safe (`flatpak info org.pwsafe.pwsafe`) e.g. _Runtime: org.freedesktop.Platform/x86_64/23.08._ Each individual flatpak sets on which runtime it will be running.
- Individual flatpak (`flatpak list --app`) e.g. Password Safe flatpak.

> I'm not quite ready to switch to that directory for interoperability reasons. So yes, I'm retaining the native ~/.pwsafe location for the Password Safe database. For now.

It is perfectly fine if you want to use some other directory for password database like ~/.pwsafe directory.

Flatpak software is trying to slowly move to the more secure model where each of the application (flatpak) has only access to its own files and not having access to whole file system (just like phone applications for example). Flatpaks are somehow sandboxed into particular part of file system. This is pretty different then installing program from .deb or .rpm when during install program has full access to the file system and if program is malicious it can have too much access, upload some files to internet etc.

By default flatpak application (because of sandbox) can only access its own directory which is `~/.var/app/INDIVIDUAL_FLATPAK_DIRECTORY` in case of Password Safe this is `~/.var/app/org.pwsafe.pwsafe/` and sub-directories. That is the reason for such a "bizarre" directory path.

If individual flatpak wants to have wider access to filesystem then flatpak package maintainer can set wider access in so called [manifest file](https://github.com/flathub/org.pwsafe.pwsafe/blob/master/org.pwsafe.pwsafe.yml), that is used to build/compile flatpak package.

We have decided that beside default Password Safe `~/.var/app/org.pwsafe.pwsafe/` directory user can:
1. Save password database file in ~/Documents/ or into one of its sub-directory (for average user).
2. Add additional permissions using e.g. flatpak command or starting flatpak with switch (for advance users).
3. Using Flatseal flatpak GUI application `flatpak install com.github.tchx84.Flatseal` and change some setting from _Filesystem_ section for Password Safe flatpak.
![image](https://github.com/pwsafe/pwsafe/assets/10895030/5be4bf42-2f77-44ba-889b-e0c6e32f5638)

Flatpak idea is to make applications more secure. For example do we really want every application we install to have access to ~./ssh directory and full access to internet (like when installing .deb or .rpm file)? We don't want, but installing .deb and .rpm we trust package maintainers they have checked source code if there is something "fishy" (and they in most of the cases don't). Flatpak is trying to do some advancement in security by involving sandboxing. There may appear some additional problems, because application developers first pack software as .deb and .rpm and then in the last step just create a flatpak and the latter one has some sandbox restrictions. From security point it is great, from stability point (because of lack of testing) this is not so great. I believe flatpak will have more and more users and then finally flatpaks will not be second class citizens from application developers point of view, but they will become first class citizens. Some Linux distributions e.g. Fedora Silverblue already have flatpak as default installation repository.

What is great using flatpak is one package and [38 main Linux distributions ](https://flatpak.org/setup/) are covered. If we additionally count flavors/spins like Gnome, KDE, etc we quickly get to 100 Linux distributions all having the same package (flatpak package).

Flatpak is still not perfect, because Linux distributions are using different flatpak software versions, distributions are using different theming (that can affect flatpak behaviour like some button is wider then width of the window on some larger font theme) and similar. But flatpak is rapidly improving and more and more application developers see this as perfect solution for distributing Linux software.
