### ISSUE TITLE
[mac] XML export regression

### ISSUE THREAD

**Issue by nobugshere** [pwsafe/pwsafe#1387]
When built from the current master, all string values in an XML export include the null terminator.  This prevents the file from being imported.
Happens with pwsafe-cli and the GUI app.
Does not happen with the 1.19.1 release build.
Tested on: macOS M1Max Sonoma 14.6.1, Xcode 15.4, wx 3.2.4

Here is a snippet from "diff -a master_version 1.19.1_version".  Note: '^@' is an ASCII nul character.
```
23,26c23,26
< ^@ <!--
<      Export of data was restricted to certain fields by the user.^@
<      The user specified that the following fields be excluded from the export:^@
<      ^@
---
>  <!--
>      Export of data was restricted to certain fields by the user.
>      The user specified that the following fields be excluded from the export:
>
30,31c30,31
<               <title><![CDATA[Specific^@]]></title>
<               <password><![CDATA[asd^@]]></password>
---
>               <title><![CDATA[Specific]]></title>
>               <password><![CDATA[asd]]></password>

```

**Comment by ronys** [comment]
@huven - I suspect this is due to the changes you've made to src/os/mac/utf8conv.cpp - care to take a look?
The Windows and Linux builds are unaffected.

**Comment by huven** [comment]
Yes, will look at that tomorrow. Thanks!

**Comment by huven** [comment]
@ronys looks like the reason is inconsistent usage of pws_os::wcstombs:

The XML export does UTF8 conversion (of course) and comes at line 47 of core/UTF8Conv.cpp:
size_t wcLen = data.length()+1;

Why is wcLen incremented by one. Just compare for instance with line 127 in core/Util.cpp:
txtlen = text.length();

In the first case the pws_os::wcstombs function gets a length parameter that includes the NUL character, which is actually a valid unicode character and therefor included in the output by the core foundation functions.

What do you prefer, fixing the callers to use pws_os::wcstombs consistently, or allowing the variation in the parameter and making sure all the os-implementations know how to deal with that?

**Comment by ronys** [comment]
Thanks for looking into this @huven.

The '+1' makes sense for Windows, which calls WideCharToMultiByte in os/windows/utf8conv.cpp. There, the ending NUL is useful (see https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte).

So I think that the right thing would be to adjust the mac implementation to lop off the last NUL character, as it's in the wide char input, so I don't think it can break the encoding.

**Comment by huven** [comment]
Thanks for the pointer to the Windows API @ronys I guess those semantics made sense at the time that API was designed..

I will create a new PR adding the check for the NUL character.

BTW: the Windows and Linux implementations also differ (which apparently does not have impact on the XML export), but in theory that could lead to other subtle bugs. The Linux implementation basically ignores the srclen input and always returns a NUL terminated string whereas Windows only if it is included in the input.

As Mac is a BSD-derivative, I'll keep the semantics as close as possible to Linux by ignoring the NUL character in the input.

If you prefer that the Mac implementation follows the Windows semantics (instead of Linux), let me know!

**Comment by huven** [comment]
Staying close to the Linux semantics is best, there is code in other places that makes corrections based on _MSC_VER

Will send a PR that checks for NUL characters and link it here.

**Comment by huven** [comment]
@nobugshere can you please retry with #1388  applied?

**Comment by nobugshere** [comment]
That works better.  The CLI and GUI versions match the output from their respective 1.19.1 counterparts.  However, the CLI and GUI outputs don't, exactly, match each other.  But, that's a different issue :-)
