### ISSUE TITLE
Mac binaries

### ISSUE THREAD

**Issue by mu22le** [pwsafe/pwsafe#345]
Hi, 
I see instructions to build the program on a mac os x but no mac binaries. Is there a reason for that? Can you provide mac binaries for your next release?

**Comment by seamusdemora** [comment]
Since my "conversion" a few years ago, I have wished for a mac os version of **pwsafe**. Yeah - I know about the Java version... I use it, but I don't particularly like it. It omits features in the Windows version, and has some irrational behavior for a mac app. I began following this repo after learning of the unix version, and my hopes have risen due to the mac os' *nix "genes". So - fingers crossed for any uptick in mac support!

**Comment by mmcguill** [comment]
Hi, 

I just came across this... shameless plug, I'm the author of Strongbox Password Safe iOS and Mac applications available here: 

https://github.com/mmcguill/StrongBox

I had the same issues you did when I moved to the Apple 'eco-system' so I built these apps for myself mostly, but other people seem to find them handy.

You can find them on the App Store or here (https://strongboxsafe.com). I thought they might be useful for you if you're stuck without a Mac/iOS password safe client.

All the best,
-Mark

**Comment by seamusdemora** [comment]
Not trying to sound bitchy, but could someone please explain what is going on with PasswordSafe for macOS? 

How do I track progress? Where's the source tree? (or is there one?) Where do we find .dmg installers? 

When I go to the [website](https://pwsafe.org/) I don't find the download - but the pretender `pwSafe` is listed as available through the App Store (no thank you). 

I'm still using the Java version, but that seems wacked out, too!: Last Update: 2017-11-23, reported not to work on BigSur. I've apparently got `ver 0.9.0 SNAPSHOT`, but when I visit [this page](https://sourceforge.net/projects/passwordsafe/) hovering over the `Download` button offers to download `PasswordSafe SWT ver 0.6` - an older Java version!?!

On Aug 1 Ronys sent me a link [679](https://github.com/pwsafe/pwsafe/issues/679) to d/l a .dmg. It worked, but I assumed this is an alpha or early beta version that was still being prepared for release. Since then, I see nothing - no announcements (which I follow here thru GitHub), no download links, nothing. 

This is all a bit confusing to me. Can someone clarify this - or point me to a source to monitor for announcements?

**Comment by ronys** [comment]
Here's the deal:

1.  The code here can be compiled and run under MacOS (based on wxWidgets, same as Linux)
2. The "pretender" took this project's code and build a version better tailored to mac/iOS
3. Until recently, I had no way to build packages for MacOS. Lately GitHub has added an automatic service that builds such packages
4. For the latest release, I've taken the package built by GitHub, ran it through VirusTotal and uploaded it to the release page (https://github.com/pwsafe/pwsafe/releases/tag/3.53.0)
5. Any feedback on this package appreciated.

**Comment by seamusdemora** [comment]
@ronys : Thanks for the explanation, and thanks for PasswordSafe! I've just downloaded the [3.53 dmg from your website](https://github.com/pwsafe/pwsafe/releases/download/3.53.0/pwsafe-3.53.0.dmg) & will post my feedback/observations as soon as I'm able. FWIW, you might see a lot more activity on this d/l if it were more prominent on your website.

I try to completely avoid the "App Store", so the "pretender's" code has no appeal for me.

**Comment by ronys** [comment]
As this is the first version with a dmg, I'd like to get feedback before pushing it on the website.

Appreciate your time & effort in checking this out.

**Comment by mu22le** [comment]
Hi,
I just downloaded and tried to run the new mac binary on my 2013 MacBook Pro (Mojave 10.14.6) but the app crashes on startup. The standard apple crash report is in attachment, it looks like we have a different /usr/lib/libobjc.A.dylib. Let me know if you need more information.

[pwsafe_crash.txt](https://github.com/pwsafe/pwsafe/files/5200341/pwsafe_crash.txt)

**Comment by ronys** [comment]
@sauravg - can you help here? The dmg worked fine for another user, but I don't know what version of MacOS he was running.

**Comment by sauravg** [comment]
This is likely due the fact that the wxWidgets binaries used by the dmg were built on/for macOS 10.15. These binaries were installed with homebrew.

The only alternative, as far as I can tell, is to build wxWidgets ourselves. That requires better understanding of Github workflows than I currently have.

**Comment by seamusdemora** [comment]
Please take this as a comment, not a demand, not as an indignant or ungrateful user. AFAIK, wxWidgets is fine, though I must also say I don't know much about it! With respect to homebrew however: *that is a non-starter for me personally*. I've had bad experiences with homebrew, and I cannot/will not use it (fwiw I use MacPorts, and have had a v. good experience).

REF "dmg worked fine for another user": If that comment refers to the [earlier copy I d/l here](https://github.com/pwsafe/pwsafe/issues/679#issuecomment-669425975), then I am that other user. The only system that I have tried this on in macOS Catalina (10.15.6). It worked fine for me on this system; caveat: no extensive or extended testing done.  

I also have a Mojave system (10.14.x), and a High Sierra system (10.13.x) that I can test. Please let me know what you would like me to do - I'll try, at least. The next OS - due to be released this later this year - is macOS 11/"Big Sur"; I have no intention of trying that anytime soon. "Big Sur" is in Beta, currently being tested by "developers".

**Wrt the DMG referenced here**, which I believe is the same one I d/l from your website a couple of days ago: This app opens and runs successfully on my macOS Catalina (10.15.6) system; same caveat as before. 

A couple of things which you probably know... I mention them here only because @ronys indicated this project was being compiled on GitHub's servers as (I assume) the project has no mac hardware of its own. 

Thing 1: Know that "installation" on Catalina requires the user understand how to circumvent Apple's block on installing "unsigned" apps. This is not particularly difficult now, but I believe it will be getting harder - or at least different - if recent experience w/ Apple is any indication. 

Thing 2: Longer term (a year??), jungle drums say Apple is transitioning their mac hardware from Intel-based to ARM-based.

**Comment by ronys** [comment]
I don't know how to take this discussion further, except to note that the other user contacted me via another channel (not GitHub).

**Comment by seamusdemora** [comment]
@ronys : No need to take it any further. I only wanted to make sure my feedback was received & thought I'd put "my 2 cents worth" in the mix.

Cheers!

**Comment by KaiZin2018** [comment]
Can we close this?
