### ISSUE TITLE
Tool tips missing

### ISSUE THREAD

**Issue by peter-hb** [pwsafe/pwsafe#409]
Running passwordsafe-debian-1.03.0-BETA.amd64 under Debian 9.3 with KDE Plasma, tool tips appear as empty boxes. Experimenting with Gnome reveals correct display of text. One might assume that this is a Plasma problem -as it might be - but the text boxes are partially transparent and any same coloured text might be expected to at least partially obscure the underlying image(s), but this is not the case: the boxes are truly empty.

This is not an earth shaking problem, but I thought you might like to know about it before releasing the anticipated new release.

Regards

Peter HB

**Comment by rafaelx** [comment]
I was faced with the same problem and noticed this issue only when starting my own build of the application from command line. Running the installation procedure for the same build and starting the program via application starter leads to correctly shown tooltips.

What might help in your case is to disable "Apply colors to non-QT-applications" in "Appearance" -> "Colors" -> "Options".

The conclusion is, that this problem is not caused by the implementation of pwsafe, because other not native applications are also affected. See also [Bug 355540](https://bugs.kde.org/show_bug.cgi?id=355540) for more information, progress and status of this issue.

**Comment by peter-hb** [comment]
Once I worked out that you meant "System Settings>Appearance>Colour>Apply..." it solved my problem. Thanks for the tip.
Issue closed.
