### ISSUE TITLE
Feature: auto-close database (file) upon minimize/lock/idle?

### ISSUE THREAD

**Issue by scottcopus** [pwsafe/pwsafe#441]
Hi,

I see there's options to lock the database after minimize, lock, and idle.  However, for people that use a file-sync service like OneDrive, Google Drive, Dropbox, etc., I think that auto-closing the file itself would be a nice option to have if using it with these services.  I know I've had issues with OneDrive with sync issues myself, but that could mainly be a crappy OneDrive issue.  I've tried the open-as-readonly.  I would be ok with using this feature if there was also an option that didn't require re-entering the master combination password again.  BTW, I found a bug with this... after unchecking the "Open database read-only by default" in Options, the combination dialog still has the "read-only" checkbox checked by default.

cheers,
Scott

**Comment by surfaceowl** [comment]
+1 for this!

This would eliminate `conflicted copy` problems on Dropbox... which is easy to trigger as pwsafe keeps the pwsafe database open when the app is minimized.

...assuming two users of a shared pwsafe database on Dropbox:
...user1 opens pwsafe and makes an edit - because pwsafe minimizes and keeps the database open, it is easy for user2 to create a conflicted copy if they open pwsafe and make another edit on a different record in their local dropbox.

it is easy for user1 to forget they even have pwsafe open and running -- so would be great if pwsafe would just close the file and be done with it.  Re-opening the file if needed is quick, as these files are very small.

if pwsafe closed the database file when the app was minimized, the frequency of conflicted copies would be greatly reduced.

**Comment by alexis-m** [comment]
I have a feeling that this has already been the behaviour for some time. I don't remember having problems with OneDrive.
I ran v3.45 and v3.58 (the latest) under ProcMon to confirm. I see that that pwsafe opens a db file, reads it, and closes it. Then browsing the entries don't trigger new opens.

**Comment by scottcopus** [comment]
> 

Great, if you've confirmed the db file gets closed @ minimize/lock/idle, then go ahead and close this one.
Cheers!
