### ISSUE TITLE
Failed installation on Debian Buster (Testing) of passwordsafe-debian-1.05.0-BETA.amd64.deb

### ISSUE THREAD

**Issue by peter-hb** [pwsafe/pwsafe#470]
Attempted install of passwordsafe-debian-1.05.0-BETA.amd64.deb failed because of missing dependencies, namely "libxerces-c3.1 (>= 3.1.1-1+b1)". The Buster release has "libxerces-c3.2". Given that 3.2 is later than 3.1 I'm confused by the ">=" not accepting '2' as greater than '1'?

This report is for information only: I can circumnavigate the problem without much difficulty.

**Comment by ronys** [comment]
Odd. A patch that won't break the installation on Debian stable would be nice.

**Comment by peter-hb** [comment]
Thanks for that. I hadn't realised that it was in the Buster repository and I'm now a happy chappie.

I too thought of modifying the control file, but couldn't see a way of making it bi-distro? The question now is, is it worth the effort given the availability in the repository?

**Comment by bblough** [comment]
Not "bi-distro" per se, but since the xerces version seems to be the main hangup, I think it's just a matter of specifying that either xerces packages is allowed.  So instead of "xerces-c3.1" in the Depends field, it would be "xerces-c3.1 | xerces-c3.2"

I don't think it's really that much effort so I'll do it. Obviously it's not really needed for Debian or it's derivatives since working versions are in the archive, but some people do like to download from here, so it's worth fixing here for them.

Anyway, thanks for pointing out the issue.

**Comment by bblough** [comment]
Upon further investigation, this will be more difficult than I thought. The program links against libxerces-c-3.1.so, so installing on a system with only libxerces-c-3.2.so will not work without re-linking.  One workaround might be to link instead against libxerces-c-3.so, which in Debian, will symlink to whatever version is installed.  The Depends field in the control file would still restrict 3.1  to the minimum required version, or 3.2, whichever is available.

Unfortunately, I have no idea how to do this (or anything, really) with cmake, so unless someone can chime in with the info, it will probably take me a while to get around to figuring it out.

**Comment by hansfn** [comment]
I think this is unsolvable since the package has changed name - not only version. This is different from the libcurl problem. And there is no /usr/lib/i386-linux-gnu/libxerces-c-3.so - I just tested by installing "libxerces-c-3.2". (Did you confuse it with the standard symlink libexample.so to libexample.so.<major>? It seems Debian doesn't provide that link without installing the corresponding dev-package.)

Anyway, I suggest that you either

1. Provide a deb pakage just for the latest (stable) version of Debian and clearly marks it as so or
2. Stop providing deb pakacages (for Debian) since this program is already included in Debian.

**Comment by ronys** [comment]
I've just released 1.08.2 which specifically supports Buster.
Since Debian is my primary Linux development environment, I don't think I'll stop building packages for it...
