### ISSUE TITLE
Clearify "Helping Out" section of Readme

### ISSUE THREAD

**Issue by hansfn** [pwsafe/pwsafe#565]
It's unclear to me if you want issues to be posted here on Github or on Sourceforge. And if both locations are used, I hope you can reconsider and only use one of them - to avoid duplicate issues and wasted time for you and your reporters.

PS! After reading the readme it's actually unclear what is the master repo, but https://pwsafe.org/readmore.shtml states that "Currently the main source repository is on GitHub, with SourceForge serving as a backup repository."

**Comment by ronys** [comment]
I'm really agnostic as to where the issues are posted. What I see is that developers tend to post issues on GitHub, and non-technical users on SourceForge. The master project repo is indeed on GitHub, with SF serving as a backup.

SF had problems a couple of years ago, technical and otherwise, but they seem pretty stable recently.

**Comment by rafaelx** [comment]
Is there anything that needs further clarification or a documentation file that needs updating?
