### ISSUE TITLE
database window does not open automatically on Mac after password successfully entered

### ISSUE THREAD

**Issue by tinker2much** [pwsafe/pwsafe#605]
You successfully enter the password in the initial window, but the next window for the opened database does not show up - the initial password entry window has gone away - there's nothing showing at all until you click on the password safe icon in the dock AGAIN, THEN the window showing the opened database appears.  

MacOS Catalina 10.15.1, built 2019/11/12 from commit dce41c7, Xcode 11.2.1, wxWidgets-3.0.4.tar.bz2.

**Comment by woowoo803** [comment]
I am seeing the same issue on 3.53.0 on a mac running Cataliona 10.15.6.

**Comment by seamusdemora** [comment]
I may be seeing the same thing, but in a different way?? Note that I have "installed" pwsafe.app in my user's `Applications` folder so that it shows up in Launchpad. I had to beat Apple's "security" back, but it now starts without interference from Mr. Cook & co. 

Probably irrelevant, but I'll mention it anyway: I still have the SWT/Java version of PasswordSafe on my system.

Here's what I see on my macOS Catalina 10.15.6:

1. When I start pwsafe.app, I get the correct window/dialog with password entry field. When I enter the password correctly, the first time, it opens correctly, and I see my password data.

2. When I close the pwsafe.app, the data disappears, leaving me with a blank window:
<img width="622" alt="Screen Shot 2020-09-16 at 3 27 06 PM" src="https://user-images.githubusercontent.com/14911811/93389277-8e238580-f831-11ea-8d04-24454edc425a.png">
Afterwards, I "Quit" the app from the menu bar, and the pwsafe.app icon disappears from the dock (bottom of screen).

3. When I re-start pwsafe.app I see the password file & master password entry dialog as normal. But after I enter the password, I see this: 
<img width="486" alt="Screen Shot 2020-09-16 at 3 24 56 PM" src="https://user-images.githubusercontent.com/14911811/93389653-1013ae80-f832-11ea-8b90-9052bca891d1.png">

4. I click to clear that error, and the dialog disappears - there is no other pwsafe.app window visible, but the pwsafe.app icon is still showing "active" (black dot below the icon) in the dock. If I click on this icon, the "main" pwsafe screen opens with all of the password data. 

Hope this is clear. I know you guys don't have a Mac to test with, so I can see this would be tough to debug! 

Let me know if I can do anything further.

**Comment by seamusdemora** [comment]
I was visiting today for the #690 update, and while I'm in the neighborhood thought I'd drop in here. I see that I've missed nothing, so I'll only say that my offer to test still stands, and if my explanation isn't quite clear I'll try to improve that.

**Comment by woowoo803** [comment]
This issue is still present on the 1.12 release.

**Comment by seamusdemora** [comment]
@woowoo803 👍  That's disappointing... I was hoping to ditch my Java SWT version soon, but...

**Comment by KaiZin2018** [comment]
Please double check with latest version and close when problem is fixed or explain if not

**Comment by tinker2much** [comment]
I just built on Catalina using the latest from git (4801cbff1). The problem persists as originally reported, when starting from an icon in the dock. 
NOTE: I did happen to discover that if I started the new app from Terminal by saying "open ./pwsafe.app", the main window does open automatically after successfully entering the password.  In fact, this seems to be true of even previous versions, such as those I built on 2021/01/09, 2020/08/15, and 2019/11/12 as well. (I don't have the commits available for those.) 
I hope this fact is interesting, and helps you solve the original and persistent problem.

**Comment by KaiZin2018** [comment]
Can you tell me version of wxWidgets and version of Xcode?

**Comment by tinker2much** [comment]
wxwidgets installed via homebrew:
/usr/local/bin/wx-config -> ../Cellar/wxmac/3.0.5.1_1/bin/wx-config

Xcode:
Version 12.4 (12D4e)

OS
Catalina Version 10.15.7

Here's another puzzling fact - My Mac Mini had been off, and I had to boot it up to make this reply. I clicked on my Pwsafe icon to get my GitHub password, I entered the password, and the succeeding window opened up right off! But every time after that I closed the app and clicked again, I had to click the icon again AFTER successful password entry to get that window. I don't know what to make of that. I hope it means something to you.

**Comment by tinker2much** [comment]
The procedure I followed was this, in case I'm forgetting something, or doing something unnecessary:

        git pull
        open xcode project
        it automatically and apparently successfully built
        renamed the old app in /Applications to pwsafe_20210109.app
        copied the new build of pwsafe.app to "/Applications" from
                /Users/<myname>/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-.../Build/Products/Release/pwsafe.app
        it didn't work, basically MacOS said there's nothing in that app (and there wasn't) 
        I cleaned the project and manually chose to build it again
        repeated the above steps to move the built app
        give it permission to access Documents when asked
       it seemed to work, although, I thought, with the same old problem

**Comment by tinker2much** [comment]
A side note: when I build the latest from git on other platforms (Debian ARM or Debian x86), the version on the login screen occasionally goes up - 1.12 or 1.13 elsewhere. Here, it never changes from "V0.01 OS X" which makes it really hard to verify which version you're running.

**Comment by KaiZin2018** [comment]
I have double checked with wxWidgets 3.0.5 and had been able to reproduce. Running wxWidgets 3.1.4 and 3.1.5 (GitHub actual development version) the problems is not present any more. It looks like an issue in "old" wxWidgets library - I tried a little bit around but had not been able to find a fix by calling additional functions from wxWidgets 3.0.5. The only solution seems to be the usage of version wxWidgets 3.1.4 or newer.

**Comment by tinker2much** [comment]
Since 3.14 was not available from homebrew, only 3.05 and HEAD, I downloaded the 3.14 source for building from scratch - wxWidgets-3.1.4.tar.bz2
	I followed their build instructions at /Users/<myname>/Documents/wxWidgets-3.1.4/docs/osx/install.md
		mkdir build-cocoa-debug
		cd build-cocoa-debug
		../configure --enable-debug
    		make   << except here I added "-j 4"
	cd pwsafe/Xcode
	./generate-configs -d /Users/<myname>/Documents/wxWidgets-3.1.4/build-cocoa-debug/wx-config > pwsafe-debug.xcconfig
	./generate-configs -r /Users/<myname>/Documents/wxWidgets-3.1.4/build-cocoa-debug/wx-config > pwsafe-release.xcconfig
	open the pwsafe project in Xcode
		open pwsafe-xcode6.xcodeproj
	clean the build folder
	build
	build succeeded!
        rename the old app in /Applications to pwsafe_20210312.app
        copy the new working build of pwsafe.app to "/Applications" from
                /Users/<myname>/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-bxtccazdtfkcmhgenalcnsfvjyqc/Build/Products/Release/pwsafe.app
        give it permission to access Documents when asked

And that fixed the issue. Thank you!

Except it still reports itself on the login dialog and in "About" as "V0.01 OS X". My other recent builds on Debian x86 or Raspberry Pi OS  on ARM (a modified Debian Buster) report themselves as 1.12 or 1.13?
