### ISSUE TITLE
DPI scaling

### ISSUE THREAD

**Issue by Wouterdek** [pwsafe/pwsafe#649]
At least on Windows, this application is not properly DPI aware when using 2 monitors with different DPI settings.  As the [Microsoft documentation explains](https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows), applications should rescale based on the DPI of the monitor the window is located on. It seems wxWidgets supports this, as I was able to find [a resolved issue](https://trac.wxwidgets.org/ticket/17721) and [a pull request](https://github.com/wxWidgets/wxWidgets/pull/334) related to this, but pwsafe does not.

The result is that the application is either very blurry or pixelated. See [this screenshot](https://user-images.githubusercontent.com/913101/79688361-264f1b80-824e-11ea-97c8-33558751d54a.png) for an example.

Luckily, as you can see in [this small commit](https://github.com/mooction/MyNotePad/commit/cbf9a9814ad97107d4ac5864ce89ea9f29222dc6) from a similar wxWidgets application, this may be easy to resolve.

**Comment by rafaelx** [comment]
Thank you for the very detailed description.

As far as I know, the Windows version is based on the MFC, whereas the Linux version is implemented with the Wx framework. The Wx based solution can also be created under Windows.
It would be interesting to know how the Wx-based version behaves in this regard on a Windows and Linux operating system.

However, based on the screenshot, I would assume that this bug report mainly targets the Windows version.

**Comment by ronys** [comment]
The problem here is that when we made PssswordSafe "DPI aware" per Microsoft's API for this, it broke the toolbar icons for very high resolution displays. As I currently don't have such a display, I can't properly debug this, so I've reverted the fix.

**Comment by ronys** [comment]
This should be fixed in 3.54.1

**Comment by hansfn** [comment]
Sorry to comment on a closed issue. Will create a new one if my problem isn't related.

I'm running Password Safe 3.61 on Windows 10 Pro. I have a laptop with scaling 150 % under "Scale and layout" in the display settings. At work, the laptop is connected to an external, bigger monitor with scaling 100 %. (I don't think scaling is related - just providing info.) 

My problem is that if I start Password Safe (PS) on the laptop and then connect the external monitor, the text in PS is very small when dragging it to the external monitor - see screen shot

<img width="130" alt="PasswordSafe-small-text" src="https://user-images.githubusercontent.com/92755/210994277-96b755e6-362b-4e11-9159-e8b408b5d464.png">

If I start PS when the external monitor is connected everything is fine - the text in PS has the expected size. And even disconnecting and reconnecting the external monitor doesn't change this. It seems some screen property is preserved even if the display situations changes.

PS! I don't experience this with other Windows programs. I'm a very happy user of Password Safe, using the Android port too, but this is turning into a problem as I'm getting older and I don't enjoy very small fonts anymore :-) Changing scaling in display settings doesn't work because then text in other applications get too big.
