### ISSUE TITLE
Fedora 32 tray icon is not shown.

### ISSUE THREAD

**Issue by ykne** [pwsafe/pwsafe#664]
Something changed in Fedora 32 GNOME desktop, Fedora 31 shows tray icon. Other applications I checked like Xpad and signal-desktop-1.31 show tray icon as before. Of course gnome-shell-extension-topicons-plus-27-1.fc32.noarch is required to begin with.
Does anyone know what code in pwsafe is responsible for tray icon?

**Comment by rafaelx** [comment]
The relevant code has not been changed for a long time, but the issue with the tray icon on the Gnome desktop may be related to error report [1443](https://sourceforge.net/p/passwordsafe/bugs/1443/).

**Comment by ykne** [comment]
It may be related but that error has no resolution, as if tray started to work again by itself. Tray icon code may need to be investigated. Does tray come from wxWidgets or directly from pwsafe?

**Comment by ronys** [comment]
The former:
`class SystemTray : protected wxTaskBarIcon
`

**Comment by ykne** [comment]
Should the bug be filed against wxWidgets then? I wonder if there is a test case for tray icon in wxWidgets...

**Comment by rafaelx** [comment]
As far as I know, it is a design decision of the GNOME project to no longer support legacy applications or non-native GNOME applications in the system / symbol / icon tray. Perhaps there is a general technical solution for this using D-Bus or any libraries, but this should be provided by the wx library via a uniform API. This may be technically difficult to implement for a wide variety of desktops, for which different approaches may exist. Due to these technical difficulties, the TopIconsPlus project was apparently [discontinued](https://github.com/phocean/TopIcons-plus/issues/91).
When I look at the existing bug [reports](https://trac.wxwidgets.org/search?q=wxTaskBarIcon+ubuntu) on the wxWidgets bug tracker (especially [15644](http://trac.wxwidgets.org/ticket/15644) and [17879](https://trac.wxwidgets.org/ticket/17879)), it gives the impression that there isn't much motivation to solve this problem in wxWidgets. Of course, my impression can also be wrong.
However, pwsafe relies on [wxTaskBarIcon](https://docs.wxwidgets.org/3.0/classwx_task_bar_icon.html) provided by wxWidgets, as already indicated by ronys, so I would tend to create a bug report for wxWidgets.

**Comment by ykne** [comment]
I tried to run test scenario listed in [15644](http://trac.wxwidgets.org/ticket/15644) but it failed with an error:
```$ python2 /tmp/TaskBarIcon.py
Traceback (most recent call last):
  File "/tmp/TaskBarIcon.py", line 1, in <module>
    import wx
  File "/tmp/wx.py", line 14, in <module>
AttributeError: 'module' object has no attribute 'TaskBarIcon'
```
Could anyone familiar with wx make this script or a basic c/c++ test case running?

**Comment by rafaelx** [comment]
If you [download](https://www.wxwidgets.org/downloads/) wxWidgets you will find a folder with many examples. One of them targets the taskbar.

**Comment by ykne** [comment]
Any updates? I found a set environment variable GDK_BACKEND to x11 workaround in https://bugzilla.redhat.com/show_bug.cgi?id=1389875 but all other applications I am using work just fine in GNOME Wayland without it.

**Comment by ykne** [comment]
Actual workaround: update pwsafe.desktop file and insert `env GDK_BACKEND=x11` between `Exec=` and `pwsafe`:
`Exec=env GDK_BACKEND=x11 pwsafe %f`

**Comment by ronys** [comment]
Applied @ykne 's workaround in commit 50788f7db

**Comment by ykne** [comment]
Tested on fresh new Fedora 34 with its gnome-shell-extension-topicons-plus - workaround seems no longer needed.
