### ISSUE TITLE
Error configuration file not found

### ISSUE THREAD

**Issue by oxcelovel** [pwsafe/pwsafe#826]
this way windows shortcut not work anymore in 3.58.0 C:\PasswordSafe\pwsafe.exe -g pwsafe.cfg
need include full path to config file C:\PasswordSafe\pwsafe.exe -g C:\PasswordSafe\pwsafe.cfg

**Comment by B00ze64** [comment]
Does this make running password safe from a USB device impossible if you want to pass a config file?
I do exactly this in a CMD script: _START /MIN pwsafe.exe -r xxx.psafe3 -h Public -u MyUser -g portable.cfg_
I need this to be pathless since there's no way to tell the drive letter that gets assigned...

**Comment by B00ze64** [comment]
@oxcelovel What happens if you try -g .\pwsafe.cfg ? (provided your shortcut's "Start In" is correct)

**Comment by B00ze64** [comment]
I just updated from 3.57 and option -g seems to work correctly...
