### ISSUE TITLE
version 1.4/1.5 stopped working after recent Mint 21 update

### ISSUE THREAD

**Issue by Sirjeff2000** [pwsafe/pwsafe#882]
I recently did a fresh install on an HP laptop (AMD processor) and installed version 1.14 of pwsafe. It worked fine until I applied the most recent updates. I started having a problem that after launching pwsafe, I could no longer type in my password and PWsafe would freeze. Out of desperation, I installed the windows version through Playonix so that I cold access my passwords. I have no idea what caused the problem but I have anpother HP laptop with an i7 processor that works flawlessly even after the latest update. Any suggestions would be greatly appreciated.

**Comment by ronys** [comment]
Is your other laptop running the same version of Mint?
Do the system logs (/var/log/messages, /var/log/syslog, etc.) show any errors?

**Comment by peterkelley519** [comment]
Hi - I've been having a similar (or same) problem. I'm trying to piece together what happened. I think I had version 1.14 of pwsafe and mid-September updated to 1.15.  I'm running Linux Pop!OS 22.04 . The problem started around the same time, mid-September, but sometimes (only occasionally) behaves normally. 
I open the PasswordSafe, and it seems to be frozen, but I've found it's actually extremely slow to take the combination in, or any other mouseclicks etc. (30-90 second delay, sometimes indefinite).
No other applications are behaving this way, so I'm trying to figure out if it's got to do with my system or something particular that's happening to PwSafe.
Is there anything in particualr to look for in the syslog, or another log/setting?
Best Regards!

**Comment by peterkelley519** [comment]
Not two minutes after I posted last, I was looking at /var/log/syslog and saw messages concerning my USB Hub, and though I didn't think it was likely related to my issue. But I figured I should try disconnecting the USB Hub. I opened up PWSafe and to my surprise it worked normally! closed PwSafe and then plugged the Hub in again, reopened PwSafe and it was stuck again. Repeated, because...science. Results confirmed - it appears something about my usb hub is messing with the input of pwsafe.
I have no idea what the significance of the messages are (they look like err msgs). I'll attach them.
Also - I have found no other applications that are affected by this.
@Sirjeff2000  - any chance it's something similar? 
and 
@ronys - Thank you for all the work you do with this! Any insight regarding the error msg?
Pete
[var_log_syslog_segment.log](https://github.com/pwsafe/pwsafe/files/9815645/var_log_syslog_segment.log)

**Comment by peterkelley519** [comment]
Getting closer to the [possible] cause of the problem. 
Also I tried another brand USB hub and it all worked OK. In my case I'm sure it has to do with something funky with the other USB hub that's tripping up PwSafe.
From ronys:

> Indeed, PasswordSafe polls the USB subsystem to detect the presence of a Yubikey device, so problems there can slow things down.
You can build a version of PasswordSafe without Yubikey support, per instructions in README.LINUX.DEVELOPERS.md

ref :  [https://sourceforge.net/p/passwordsafe/discussion/134801/thread/d7884b5a98/](url)

**Comment by ronys** [comment]
Hm. I think I'll add a command line flag and/or env variable to disable USB polling without a special build.
